//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSonic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("theori.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter] Change Primary Binding.
        /// </summary>
        internal static string SecretMenu_BindingChangePrimary {
            get {
                return ResourceManager.GetString("SecretMenu.BindingChangePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Secondary Binding [Control + Enter].
        /// </summary>
        internal static string SecretMenu_BindingChangeSecondary {
            get {
                return ResourceManager.GetString("SecretMenu.BindingChangeSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Management.
        /// </summary>
        internal static string SecretMenu_ChartManagementTitle {
            get {
                return ResourceManager.GetString("SecretMenu.ChartManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Controller Bindings.
        /// </summary>
        internal static string SecretMenu_ConfigureControllerBindings {
            get {
                return ResourceManager.GetString("SecretMenu.ConfigureControllerBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Configuration.
        /// </summary>
        internal static string SecretMenu_InputBindingConfigTitle {
            get {
                return ResourceManager.GetString("SecretMenu.InputBindingConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard and Mouse.
        /// </summary>
        internal static string SecretMenu_InputKeyboardMouse {
            get {
                return ResourceManager.GetString("SecretMenu.InputKeyboardMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Only.
        /// </summary>
        internal static string SecretMenu_InputKeyboardOnly {
            get {
                return ResourceManager.GetString("SecretMenu.InputKeyboardOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Method.
        /// </summary>
        internal static string SecretMenu_InputMethodTitle {
            get {
                return ResourceManager.GetString("SecretMenu.InputMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeuroSonic - Main Menu.
        /// </summary>
        internal static string SecretMenu_MainTitle {
            get {
                return ResourceManager.GetString("SecretMenu.MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option [Enter] or [START].
        /// </summary>
        internal static string SecretMenu_SelectHint {
            get {
                return ResourceManager.GetString("SecretMenu.SelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Up / Down] or [BT-A / BT-B] Navigate Menu.
        /// </summary>
        internal static string SecretMenu_UpDownNavHint {
            get {
                return ResourceManager.GetString("SecretMenu.UpDownNavHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string SecretMenu_UserConfigTitle {
            get {
                return ResourceManager.GetString("SecretMenu.UserConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Laser Hue.
        /// </summary>
        internal static string Term_Gameplay_LeftLaserHue {
            get {
                return ResourceManager.GetString("Term.Gameplay.LeftLaserHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Laser Hue.
        /// </summary>
        internal static string Term_Gameplay_RightLaserHue {
            get {
                return ResourceManager.GetString("Term.Gameplay.RightLaserHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed.
        /// </summary>
        internal static string Term_HiSpeed {
            get {
                return ResourceManager.GetString("Term.HiSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed Kind.
        /// </summary>
        internal static string Term_HiSpeedKind {
            get {
                return ResourceManager.GetString("Term.HiSpeedKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Mod.
        /// </summary>
        internal static string Term_HiSpeedKind_ConstantMod {
            get {
                return ResourceManager.GetString("Term.HiSpeedKind.ConstantMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Mod.
        /// </summary>
        internal static string Term_HiSpeedKind_ModeMod {
            get {
                return ResourceManager.GetString("Term.HiSpeedKind.ModeMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        internal static string Term_HiSpeedKind_Multiplier {
            get {
                return ResourceManager.GetString("Term.HiSpeedKind.Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiSpeed Value.
        /// </summary>
        internal static string Term_HiSpeedValue {
            get {
                return ResourceManager.GetString("Term.HiSpeedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Offset.
        /// </summary>
        internal static string Term_InputOffset {
            get {
                return ResourceManager.GetString("Term.InputOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Offset.
        /// </summary>
        internal static string Term_VideoOffset {
            get {
                return ResourceManager.GetString("Term.VideoOffset", resourceCulture);
            }
        }
    }
}
