name: .NET Core 3.0 CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          version: 3.0.100-preview8-013656

      - name: Publish
        run: dotnet publish --output ClientBuild\Win64 --configuration Deploy --framework netcoreapp3.0 --runtime win10-x64 neurosonic.sln

      - name: Package
        run: Compress-Archive -Path ClientBuild\Win64\* -DestinationPath NeuroSonic-Win64
        shell: pwsh
          
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: NeuroSonic-Win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
