name: .NET Core 3.0 CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          version: 3.0.100-preview8-013656

      - name: Build
        run: dotnet build --configuration Deploy --framework netcoreapp3.0 neurosonic.sln

      - name: Publish
        run: dotnet publish --configuration Deploy --framework netcoreapp3.0 neurosonic.sln

      - name: Package
        run: Compress-Archive -Path Clients\nsc-core3.0\bin\x64\Deploy\netcoreapp3.0\* -DestinationPath NeuroSonic
        shell: pwsh

      - name: Publish Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: NeuroSonic
          path: NeuroSonic.zip
          
      - name: Create Github Release
        uses: frankjuniorr/github-create-release-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
